#!/usr/bin/env node
/**
 * Build a fully static export of the site for shared hosting (e.g. Hostinger).
 *
 * Static hosting has no Node server, so:
 *   - the `/api/contact` route handler (POST) is temporarily moved out of the
 *     app tree so `output: 'export'` does not fail on it;
 *   - response headers are delivered via a generated `out/.htaccess`
 *     (Apache/LiteSpeed) instead of Next's `headers()`.
 *
 * The contact form submits via Web3Forms when NEXT_PUBLIC_WEB3FORMS_KEY is set
 * (see src/components/forms/ContactForm.tsx).
 *
 * Usage:
 *   NEXT_PUBLIC_SITE_URL=https://visiosolutions.net \
 *   NEXT_PUBLIC_WEB3FORMS_KEY=your-key \
 *   node scripts/build-static.mjs
 */
import { spawnSync } from 'node:child_process';
import { existsSync, renameSync, writeFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const apiDir = join(root, 'src', 'app', 'api');
const apiStash = join(root, 'src', '__api_excluded__');
const outDir = join(root, 'out');

const csp = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "connect-src 'self' https://api.web3forms.com",
  "form-action 'self' https://api.web3forms.com",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

const htaccess = `# Generated by scripts/build-static.mjs — static hosting config for Hostinger
Options -Indexes
DirectoryIndex index.html

# Force HTTPS (Hostinger provides free SSL)
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

  # Add trailing slash for extensionless paths so /about serves /about/index.html
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.+[^/])$ /$1/ [L,R=301]
</IfModule>

# Custom 404
ErrorDocument 404 /404.html

# Security headers
<IfModule mod_headers.c>
  Header set Content-Security-Policy "${csp}"
  Header set X-Content-Type-Options "nosniff"
  Header set X-Frame-Options "DENY"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  Header set Permissions-Policy "camera=(), microphone=(), geolocation=(), browsing-topics=()"
  Header set Strict-Transport-Security "max-age=63072000; includeSubDomains"
  Header set X-DNS-Prefetch-Control "on"
</IfModule>

# Long-cache hashed static assets
<IfModule mod_headers.c>
  <FilesMatch "\\.(js|css|woff2|woff|ttf|svg|png|jpg|jpeg|webp|avif|ico)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
</IfModule>

# Gzip
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml
</IfModule>
`;

function moveApiOut() {
  if (existsSync(apiDir)) {
    if (existsSync(apiStash)) rmSync(apiStash, { recursive: true, force: true });
    renameSync(apiDir, apiStash);
  }
}
function restoreApi() {
  if (existsSync(apiStash)) {
    if (existsSync(apiDir)) rmSync(apiDir, { recursive: true, force: true });
    renameSync(apiStash, apiDir);
  }
}

console.log('▶ Building static export…');
moveApiOut();
try {
  const result = spawnSync('npx', ['next', 'build'], {
    cwd: root,
    stdio: 'inherit',
    env: {
      ...process.env,
      STATIC_EXPORT: 'true',
      NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://visiosolutions.net',
    },
  });
  if (result.status !== 0) {
    process.exitCode = result.status ?? 1;
    throw new Error('next build failed');
  }
} finally {
  restoreApi();
}

if (existsSync(outDir)) {
  writeFileSync(join(outDir, '.htaccess'), htaccess, 'utf8');
  console.log('✅ Static export complete → out/  (with .htaccess)');
} else {
  console.error('✗ Expected out/ directory was not produced.');
  process.exitCode = 1;
}
