#!/usr/bin/env node
/**
 * Build a fully static export of the site for shared hosting (e.g. Hostinger).
 *
 * Static hosting has no Node server, so:
 *   - the `/api/contact` route handler (POST) is temporarily moved out of the
 *     app tree so `output: 'export'` does not fail on it;
 *   - response headers are delivered via a generated `out/.htaccess`
 *     (Apache/LiteSpeed) instead of Next's `headers()`.
 *
 * The contact form submits via Web3Forms when NEXT_PUBLIC_WEB3FORMS_KEY is set
 * (see src/components/forms/ContactForm.tsx).
 *
 * Usage:
 *   NEXT_PUBLIC_SITE_URL=https://visiosolutions.net \
 *   NEXT_PUBLIC_WEB3FORMS_KEY=your-key \
 *   node scripts/build-static.mjs
 */
import { spawnSync } from 'node:child_process';
import { existsSync, renameSync, writeFileSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const apiDir = join(root, 'src', 'app', 'api');
const apiStash = join(root, 'src', '__api_excluded__');
const outDir = join(root, 'out');

// Origin of the payment gateway's hosted checkout, e.g.
// PAYMENT_GATEWAY_ORIGIN=https://checkout.example.com. When set, the CSP allows
// the browser to submit a payment form to it; without this a "Pay now" form
// would be blocked by `form-action 'self'`. Leave unset until a checkout is
// actually wired up.
const gatewayOrigin = (process.env.PAYMENT_GATEWAY_ORIGIN ?? '').trim();
if (gatewayOrigin && !/^https:\/\/[a-z0-9.-]+(:\d+)?$/i.test(gatewayOrigin)) {
  console.error(`✗ PAYMENT_GATEWAY_ORIGIN must be a bare https origin, got: ${gatewayOrigin}`);
  process.exit(1);
}
const gatewaySource = gatewayOrigin ? ` ${gatewayOrigin}` : '';

const csp = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  `connect-src 'self' https://api.web3forms.com${gatewaySource}`,
  `form-action 'self' https://api.web3forms.com${gatewaySource}`,
  // Only needed if the gateway's checkout is embedded rather than redirected to.
  `frame-src 'self'${gatewaySource}`,
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "object-src 'none'",
  'upgrade-insecure-requests',
].join('; ');

const htaccess = `# Generated by scripts/build-static.mjs — static hosting config for Hostinger
Options -Indexes
DirectoryIndex index.html

# Force HTTPS (Hostinger provides free SSL)
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

  # Add trailing slash for extensionless paths so /about serves /about/index.html
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.+[^/])$ /$1/ [L,R=301]
</IfModule>

# Custom 404
ErrorDocument 404 /404.html

# Security headers
<IfModule mod_headers.c>
  Header set Content-Security-Policy "${csp}"
  Header set X-Content-Type-Options "nosniff"
  Header set X-Frame-Options "DENY"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
  Header set Permissions-Policy "camera=(), microphone=(), geolocation=(), browsing-topics=()"
  Header set Strict-Transport-Security "max-age=63072000; includeSubDomains"
  Header set X-DNS-Prefetch-Control "on"
</IfModule>

# Long-cache hashed static assets
<IfModule mod_headers.c>
  <FilesMatch "\\.(js|css|woff2|woff|ttf|svg|png|jpg|jpeg|webp|avif|ico)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>
</IfModule>

# Payment routes get their own out/payment/.htaccess (see paymentHtaccess below).

# Gzip
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml
</IfModule>
`;

// Directory-level rules for /payment/. Kept in their own file rather than an
// <If> block in the root .htaccess: <If> needs Apache 2.4 semantics that not
// every shared host (or LiteSpeed build) honours, and a directory .htaccess is
// understood everywhere. Authorization directives are written for both the 2.4
// and 2.2 syntaxes so an older host does not 500 on an unknown directive.
const paymentHtaccess = `# Generated by scripts/build-static.mjs — rules for the payment routes.

# Return pages carry per-transaction references in the query string, so keep
# them out of every cache and stop the reference leaking through Referer.
<IfModule mod_headers.c>
  Header always set Cache-Control "no-store, max-age=0"
  Header always set Referrer-Policy "no-referrer"
</IfModule>

# The IPN configuration file may hold a shared secret. PHP normally executes it
# and returns nothing, but deny it outright in case PHP is ever disabled here.
<FilesMatch "^notify-config(\\.example)?\\.php$">
  <IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
  <IfModule !mod_authz_core.c>
    Order allow,deny
    Deny from all
  </IfModule>
</FilesMatch>
`;

function moveApiOut() {
  if (existsSync(apiDir)) {
    if (existsSync(apiStash)) rmSync(apiStash, { recursive: true, force: true });
    renameSync(apiDir, apiStash);
  }
}
function restoreApi() {
  if (existsSync(apiStash)) {
    if (existsSync(apiDir)) rmSync(apiDir, { recursive: true, force: true });
    renameSync(apiStash, apiDir);
  }
}

console.log('▶ Building static export…');
moveApiOut();
try {
  const result = spawnSync('npx', ['next', 'build'], {
    cwd: root,
    stdio: 'inherit',
    env: {
      ...process.env,
      STATIC_EXPORT: 'true',
      // Tells the contact form it is on static hosting (no /api/contact). With a
      // Web3Forms key it submits there; without one it offers a pre-filled email.
      NEXT_PUBLIC_STATIC_EXPORT: 'true',
      NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? 'https://visiosolutions.net',
    },
  });
  if (result.status !== 0) {
    process.exitCode = result.status ?? 1;
    throw new Error('next build failed');
  }
} finally {
  restoreApi();
}

if (existsSync(outDir)) {
  writeFileSync(join(outDir, '.htaccess'), htaccess, 'utf8');

  // The payment directory must exist: /payment/success and /payment/cancel are
  // exported pages and public/payment/notify.php is copied verbatim. Fail loudly
  // if it is missing rather than shipping an endpoint the gateway cannot reach.
  const paymentDir = join(outDir, 'payment');
  if (!existsSync(join(paymentDir, 'notify.php'))) {
    console.error('✗ out/payment/notify.php is missing — the IPN endpoint would 404.');
    process.exitCode = 1;
  } else {
    writeFileSync(join(paymentDir, '.htaccess'), paymentHtaccess, 'utf8');
    console.log('✅ Static export complete → out/  (with .htaccess + payment endpoint)');
  }
} else {
  console.error('✗ Expected out/ directory was not produced.');
  process.exitCode = 1;
}
